### ISSUE TITLE
issue parameter ignores new line

### ISSUE THREAD

**Issue by ikonia** [Ericsson/puppet-module-motd#15]
using the version 1.0 release of the motd module, I have populated the issue parameter with a standard warning message.

Upon login via ssh the banner parmeter is set to /etc/issue which is popluated by this module, the issue message is displayed however there does not appear to be a new line / end of line terminator at the end of the text.

This is a current example - the text doesn't matter the issue is repeatable.

********************************************************************
* \                                                                *
* This system is for the use of authorized users only.  Usage of   *
* this system may be monitored and recorded by system personnel.   *
*                                                                  *
* Anyone using this system expressly consents to such monitoring   *
* and is advised that if such monitoring reveals possible          *
* evidence of criminal activity, system personnel may provide the  *
* evidence from such monitoring to law enforcement officials.      *
*                                                                  *
********************************************************************Last login: Thu Mar  5 14:00:31 2015 from 192.168.125.22

the last login message is normally displayed on a new line after the banner message, this works if /etc/issue is set manually outside of this module

if I cut and paste the text in the parameter into /etc/issue manually I see

********************************************************************
* \                                                                *
* This system is for the use of authorized users only.  Usage of   *
* this system may be monitored and recorded by system personnel.   *
*                                                                  *
* Anyone using this system expressly consents to such monitoring   *
* and is advised that if such monitoring reveals possible          *
* evidence of criminal activity, system personnel may provide the  *
* evidence from such monitoring to law enforcement officials.      *
*                                                                  *
********************************************************************

Last login: Thu Mar  5 14:02:57 2015 from 192.168.125.22

how can I force an EOF or  \n into this class

**Comment by ghoneycutt** [comment]
put a new line in your content.

```c
"My message.\n"
```

or in YAML in Hiera

```yaml
motd::issue_content: |
  My message


```

**Comment by Phil-Friderici** [comment]
Closing this issue as @ikonia seems to be satisfied with ghoneycutts answer.
Feel free to reopen if problem still exists.
