### ISSUE TITLE
issue parameter inserting random "\" parameter into issue variable

### ISSUE THREAD

**Issue by ikonia** [Ericsson/puppet-module-motd#16]
using version 1.0 of the motd module I set the following warning message to the issue parameter

********************************************************************
*                                                                 *
* This system is for the use of authorized users only.  Usage of   *
* this system may be monitored and recorded by system personnel.   *
*                                                                  *
* Anyone using this system expressly consents to such monitoring   *
* and is advised that if such monitoring reveals possible          *
* evidence of criminal activity, system personnel may provide the  *
* evidence from such monitoring to law enforcement officials.      *
*                                                                  *
********************************************************************

(this is just example text the same is true of any text I use)

This looks fine - however when I look at the contents of the file /etc/issue that is managed by this host, the text looks like this

********************************************************************
* \                                                                *
* This system is for the use of authorized users only.  Usage of   *
* this system may be monitored and recorded by system personnel.   *
*                                                                  *
* Anyone using this system expressly consents to such monitoring   *
* and is advised that if such monitoring reveals possible          *
* evidence of criminal activity, system personnel may provide the  *
* evidence from such monitoring to law enforcement officials.      *
*                                                                  *
********************************************************************

as you can see on line 2 a "\" has been entered, this is also displayed when you connect via ssh and the banner parameter uses /etc/issue.

**Comment by ghoneycutt** [comment]
If you are using double quotes the `\` is a control character such as `\n` for new line. If you want a backslash in your content, use single quotes or if you need double quotes, you must escape the backslash with another backslash such as `\\`

**Comment by Phil-Friderici** [comment]
Closing this issue as @ikonia seems to be satisfied with ghoneycutts answer.
Feel free to reopen if problem still exists.
